export const navItems = [
  {
    key: 'home',
    label: 'Home',
    href: '/',
    auth: false,
  },
  {
    key: 'account',
    label: 'Account',
    href: '/account',
    auth: false,
  },
  {
    key: 'address',
    label: 'Address lookup',
    href: '/address',
    auth: false,
  },
  {
    key: 'attributes',
    label: 'Attributes',
    href: '/attributes',
    auth: false,
  },
  {
    key: 'blog',
    label: 'Blog',
    href: '/blog',
    auth: false,
  },
  {
    key: 'categories',
    label: 'Categories',
    href: '/categories',
    auth: false,
  },
  {
    key: 'currencies',
    label: 'Currencies',
    href: '/currency',
    auth: false,
  },
  {
    key: 'products',
    label: 'Products',
    href: '/products',
    auth: false,
  },
  {
    key: 'reviews',
    label: 'Reviews',
    href: '/reviews',
    auth: false,
  },
  {
    key: 'signup',
    label: 'Signup',
    href: '/signup',
    auth: false,
  },
  {
    key: 'tags',
    label: 'Tags',
    href: '/tags',
    auth: false,
  },
  {
    key: 'vendors',
    label: 'Vendors',
    href: '/vendors',
    auth: false,
  },
  {
    key: 'events',
    label: 'Events',
    href: '/events',
    auth: true,
  },
  {
    key: 'messages',
    label: 'Messages',
    href: '/messages',
    auth: true,
  },
  {
    key: 'product',
    label: 'Product',
    href: '/product',
    auth: true,
  },
]
